class Event11 {
  final String id;
  final String title;
  final String description;
  final String city;
  final String category;
  final double latitude;
  final double longitude;
  final String? imageUrl;

  final DateTime date;
  final String time;
  final int price;

  const Event11({
    required this.id,
    required this.title,
    required this.description,
    required this.city,
    required this.latitude,
    required this.longitude,
    this.imageUrl,
    required this.category,
    required this.date,
    required this.time,
    required this.price,
  });

  static List<Event11> egyptEvents11 = [
    Event11(
      id: 'c1',
      title: 'Cairo Tech Summit',
      description: 'Tech conference',
      city: 'Cairo',
      latitude: 30.0444,
      longitude: 31.2357,
      category: 'Technology',
      date: DateTime(2026, 1, 15),
      time: '10:00 AM',
      price: 300,
    ),
    Event11(
      id: 'c2',
      title: 'Opera House Ballet',
      description: 'Classical dance',
      city: 'Cairo',
      latitude: 30.0425,
      longitude: 31.2242,
      category: 'Art',
      date: DateTime(2026, 2, 15),
      time: '7:00 PM',
      price: 250,
    ),
    Event11(
      id: 'c3',
      title: 'Zamalek Art Gallery',
      description: 'Modern art',
      city: 'Cairo',
      latitude: 30.0595,
      longitude: 31.2220,
      category: 'Art',
      date: DateTime(2026, 8, 22),
      time: '5:00 PM',
      price: 150,
    ),
    Event11(
      id: 'c4',
      title: 'Maadi Food Festival',
      description: 'International cuisines',
      city: 'Cairo',
      latitude: 29.9602,
      longitude: 31.2569,
      category: 'Food',
      date: DateTime(2026, 9, 25),
      time: '3:00 PM',
      price: 120,
    ),
    Event11(
      id: 'c5',
      title: 'Al-Azhar Park Concert',
      description: 'Live music show',
      city: 'Cairo',
      latitude: 30.0406,
      longitude: 31.2647,
      category: 'Music',
      date: DateTime(2026, 5, 28),
      time: '8:00 PM',
      price: 200,
    ),
    Event11(
      id: 'g1',
      title: 'Pyramids Marathon',
      description: 'Annual run',
      city: 'Giza',
      latitude: 29.9792,
      longitude: 31.1342,
      category: 'Sports',
      date: DateTime(2026, 6, 10),
      time: '6:00 AM',
      price: 100,
    ),
    Event11(
      id: 'g2',
      title: 'Sound and Light Show',
      description: 'History show',
      city: 'Giza',
      latitude: 29.9753,
      longitude: 31.1376,
      category: 'Culture',
      date: DateTime(2026, 6, 12),
      time: '7:30 PM',
      price: 180,
    ),
    Event11(
      id: 'g3',
      title: 'Giza Zoo Tour',
      description: 'Family outing',
      city: 'Giza',
      latitude: 30.0217,
      longitude: 31.2131,
      category: 'Family',
      date: DateTime(2026, 10, 15),
      time: '11:00 AM',
      price: 80,
    ),
    Event11(
      id: 'g4',
      title: 'Grand Museum Opening',
      description: 'History exhibition',
      city: 'Giza',
      latitude: 29.9949,
      longitude: 31.1189,
      category: 'Culture',
      date: DateTime(2026, 12, 18),
      time: '9:00 AM',
      price: 220,
    ),
    Event11(
      id: 'g5',
      title: 'Smart Village Meetup',
      description: 'Startups gathering',
      city: 'Giza',
      latitude: 30.0766,
      longitude: 31.0183,
      category: 'Business',
      date: DateTime(2026, 3, 20),
      time: '6:00 PM',
      price: 250,
    ),
    Event11(
      id: 'a1',
      title: 'Alex Music Festival',
      description: 'Beach music',
      city: 'Alexandria',
      latitude: 31.2001,
      longitude: 29.9187,
      category: 'Music',
      date: DateTime(2026, 4, 1),
      time: '8:00 PM',
      price: 200,
    ),
    Event11(
      id: 'a2',
      title: 'Bibliotheca Exhibition',
      description: 'Book fair',
      city: 'Alexandria',
      latitude: 31.2089,
      longitude: 29.9092,
      category: 'Education',
      date: DateTime(2026, 7, 19),
      time: '10:00 AM',
      price: 120,
    ),
    Event11(
      id: 'a3',
      title: 'Citadel Night',
      description: 'Historical tour',
      city: 'Alexandria',
      latitude: 31.2140,
      longitude: 29.8856,
      category: 'History',
      date: DateTime(2026, 7, 8),
      time: '7:00 PM',
      price: 150,
    ),
    Event11(
      id: 'a4',
      title: 'Stanley Bridge Run',
      description: 'Morning run',
      city: 'Alexandria',
      latitude: 31.2338,
      longitude: 29.9482,
      category: 'Sports',
      date: DateTime(2026, 11, 28),
      time: '6:30 AM',
      price: 90,
    ),
    Event11(
      id: 'a5',
      title: 'Seafood Festival',
      description: 'Fresh catch event',
      city: 'Alexandria',
      latitude: 31.2118,
      longitude: 29.8920,
      category: 'Food',
      date: DateTime(2026, 3, 14),
      time: '4:00 PM',
      price: 130,
    ),
    Event11(
      id: 's1',
      title: 'Industrial Innovation',
      description: 'Factory expo',
      city: 'Sharqia',
      latitude: 30.2970,
      longitude: 31.7505,
      category: 'Business',
      date: DateTime(2026, 10, 17),
      time: '11:00 AM',
      price: 200,
    ),
    Event11(
      id: 's2',
      title: 'Sharqia Horses Festival',
      description: 'Traditional horses',
      city: 'Sharqia',
      latitude: 30.5877,
      longitude: 31.5020,
      category: 'Culture',
      date: DateTime(2026, 8, 18),
      time: '5:00 PM',
      price: 100,
    ),
  ];
}
