import 'package:event_hub/model/event_model.dart';

class EventRepository {
  static final List<EventModel> allEvents = [
    EventModel(
      id: "1",
      title: "Pro Gaming Tournament",
      description: "Gaming competition event",
      location: "Cairo Tower, Egypt",
      latitude: 30.0444,
      longitude: 31.2357,
      date: DateTime(2026, 5, 15),
      time: '10:00 AM',
      price: 20,
      image: 'assets/image/gaming1.jpg',
      category: "Gaming",
    ),
    EventModel(
      id: "2",
      title: "Mobile Legends Cup",
      description: "Gaming championship",
      location: "Alexandria Stadium",
      latitude: 31.2001,
      longitude: 29.9187,
      date: DateTime(2026, 2, 12),
      time: '2:00 PM',
      price: 15,
      image: 'assets/image/gaming2.jpg',
      category: "Gaming",
    ),
    EventModel(
      id: "3",
      title: "E-Sports Masterclass",
      description: "Gaming training session",
      location: "Nasr City, Cairo",
      latitude: 30.0500,
      longitude: 31.3300,
      date: DateTime(2026, 3, 15),
      time: '6:00 PM',
      price: 0,
      image: 'assets/image/gaming3.jpg',
      category: "Gaming",
    ),
    EventModel(
      id: "4",
      title: "Flutter Dev Meetup",
      description: "Flutter community meetup",
      location: "Alexandria, Egypt",
      latitude: 31.2156,
      longitude: 29.9553,
      date: DateTime(2026, 7, 15),
      time: '5:00 PM',
      price: 50,
      image: 'assets/image/tech1.jpg',
      category: "Tech",
    ),
    EventModel(
      id: "5",
      title: "AI & Future Summit",
      description: "AI technology event",
      location: "Smart Village, Giza",
      latitude: 30.0766,
      longitude: 31.0183,
      date: DateTime(2026, 1, 18),
      time: '8:00 AM',
      price: 100,
      image: 'assets/image/tech2.jpg',
      category: "Tech",
    ),
    EventModel(
      id: "6",
      title: "Hackathon Cairo 2026",
      description: "Coding competition",
      location: "AUC Campus, Egypt",
      latitude: 30.0200,
      longitude: 31.4999,
      date: DateTime(2026, 5, 25),
      time: '8:00 AM',
      price: 10,
      image: 'assets/image/tech3.jpg',
      category: "Tech",
    ),
    EventModel(
      id: "7",
      title: "Startup Weekend",
      description: "Business networking event",
      location: "Downtown Cairo",
      latitude: 30.0444,
      longitude: 31.2357,
      date: DateTime(2026, 9, 1),
      time: '10:00 AM',
      price: 40,
      image: 'assets/image/business1.jpg',
      category: "Business",
    ),
    EventModel(
      id: "8",
      title: "Investing 101 Workshop",
      description: "Finance basics",
      location: "Greek Campus, Cairo",
      latitude: 30.0435,
      longitude: 31.2350,
      date: DateTime(2026, 11, 5),
      time: '2:00 PM',
      price: 25,
      image: 'assets/image/business2.jpg',
      category: "Business",
    ),
    EventModel(
      id: "9",
      title: "Global Trade Forum",
      description: "International trade event",
      location: "Sheraton Hotel, Cairo",
      latitude: 30.0561,
      longitude: 31.2400,
      date: DateTime(2026, 5, 15),
      time: '9:00 AM',
      price: 200,
      image: 'assets/image/business3.jpg',
      category: "Business",
    ),
    EventModel(
      id: "10",
      title: "Data Science Bootcamp",
      description: "Data science training",
      location: "Smart Village, Giza",
      latitude: 30.0766,
      longitude: 31.0183,
      date: DateTime(2026, 5, 20),
      time: '2:00 PM',
      price: 80,
      image: 'assets/image/education2.jpg',
      category: "Education",
    ),
  ];
}
