import 'package:event_hub/model/event_model.dart';

class EventRepository {
  static final List<EventModel> allEvents = [
    EventModel(
      title: "Pro Gaming Tournament",
      location: "Cairo Tower, Egypt",
      datetime: DateTime(2026, 5, 15),
      price: 20,
      imagepath: 'assets/image/gaming1.jpg',
      category: "Gaming",
      isFavorite: false,
      time: '10:00 AM',
    ),
    EventModel(
      title: "Mobile Legends Cup",
      location: "Alexandria Stadium",
      datetime: DateTime(2026, 2, 12),
      price: 15,
      imagepath: 'assets/image/gaming2.jpg',
      category: "Gaming",
      isFavorite: false,
      time: '2:00 PM',
    ),
    EventModel(
      title: "E-Sports Masterclass",
      location: "Online (Global)",
      datetime: DateTime(2026, 3, 15),
      price: 0,
      imagepath: 'assets/image/gaming3.jpg',
      category: "Gaming",
      isFavorite: false,
      time: '6:00 PM',
    ),
    EventModel(
      title: "Flutter Dev Meetup",
      location: "Alex, Egypt",
      datetime: DateTime(2026, 7, 15),
      price: 50,
      imagepath: 'assets/image/tech1.jpg',
      category: "Tech",
      isFavorite: false,
      time: '5:00 PM',
    ),
    EventModel(
      title: "AI & Future Summit",
      location: "Smart Village, Giza",
      datetime: DateTime(2026, 1, 18),
      price: 100,
      imagepath: 'assets/image/tech2.jpg',
      category: "Tech",
      isFavorite: false,
      time: '8:00 AM',
    ),
    EventModel(
      title: "Hackathon Cairo 2026",
      location: "AUC Campus, Egypt",
      datetime: DateTime(2026, 5, 25),
      price: 10,
      imagepath: 'assets/image/tech3.jpg',
      category: "Tech",
      isFavorite: false,
      time: '8:00 AM',
    ),
    EventModel(
      title: "Startup Weekend",
      location: "Downtown Cairo",
      datetime: DateTime(2026, 9, 1),
      price: 40,
      imagepath: 'assets/image/business1.jpg',
      category: "Business",
      isFavorite: false,
      time: '10:00 AM',
    ),
    EventModel(
      title: "Investing 101 Workshop",
      location: "The Greek Campus",
      datetime: DateTime(2026, 11, 5),
      price: 25,
      imagepath: 'assets/image/business2.jpg',
      category: "Business",
      isFavorite: false,
      time: '2:00 PM',
    ),
    EventModel(
      title: "Global Trade Forum",
      location: "Sheraton Hotel, Cairo",
      datetime: DateTime(2026, 5, 15, 10, 0),
      price: 200,
      imagepath: 'assets/image/business3.jpg',
      category: "Business",
      isFavorite: false,
      time: '9:00 AM',
    ),
    EventModel(
      title: "Study Abroad Fair",
      location: "El Shorouk Academy",
      datetime: DateTime(2026, 3, 12),
      price: 0,
      imagepath: 'assets/image/education1.jpg',
      category: "Education",
      isFavorite: false,
      time: '10:00 AM',
    ),
    EventModel(
      title: "Data Science Bootcamp",
      location: "Online",
      datetime: DateTime(2026, 5, 20),
      price: 80,
      imagepath: 'assets/image/education2.jpg',
      category: "Education",
      isFavorite: false,
      time: '2:00 PM',
    ),
    EventModel(
      title: "Creative Writing Class",
      location: "Maadi Library",
      datetime: DateTime(2026, 9, 25),
      price: 15,
      imagepath: 'assets/image/education3.jpg',
      category: "Education",
      isFavorite: false,
      time: '1:00 PM',
    ),
    EventModel(
      title: "Abstract Art Expo",
      location: "Giza, Egypt",
      datetime: DateTime(2026, 1, 20),
      price: 30,
      imagepath: 'assets/image/arts1.jpg',
      category: "Arts",
      isFavorite: false,
      time: '10:30 AM',
    ),
    EventModel(
      title: "Classical Music Night",
      location: "Opera House, Cairo",
      datetime: DateTime(2026, 12, 25),
      price: 60,
      imagepath: 'assets/image/arts2.jpg',
      category: "Arts",
      isFavorite: false,
      time: '8:00 PM',
    ),
    EventModel(
      title: "Photography Workshop",
      location: "Old Cairo",
      datetime: DateTime(2026, 6, 30),
      price: 20,
      imagepath: 'assets/image/arts3.jpg',
      category: "Arts",
      isFavorite: false,
      time: '2:00 PM',
    ),
    EventModel(
      title: "Cairo Half Marathon",
      location: "Zamalek, Egypt",
      datetime: DateTime(2026, 11, 5),
      price: 10,
      imagepath: 'assets/image/sports1.jpg',
      category: "Sports",
      isFavorite: false,
      time: '8:00 AM',
    ),
    EventModel(
      title: "Yoga Morning Session",
      location: "Al-Azhar Park",
      datetime: DateTime(2026, 1, 10),
      price: 5,
      imagepath: 'assets/image/sports2.jpg',
      category: "Sports",
      isFavorite: false,
      time: '11:30 AM',
    ),
    EventModel(
      title: "Tennis Open Championship",
      location: "Sporting Club, Alex",
      datetime: DateTime(2026, 2, 15),
      price: 45,
      imagepath: 'assets/image/sports3.jpg',
      category: "Sports",
      isFavorite: false,
      time: '2:30 PM',
    ),
    EventModel(
      title: "Summer Collection 2026",
      location: "Cairo Festival City",
      datetime: DateTime(2026, 9, 1),
      price: 35,
      imagepath: 'assets/image/fashion1.jpg',
      category: "Fashion",
      isFavorite: false,
      time: '12:30 PM',
    ),
    EventModel(
      title: "Model Runway Show",
      location: "Marriott Hotel",
      datetime: DateTime(2026, 5, 15),
      price: 120,
      imagepath: 'assets/image/fashion2.jpg',
      category: "Fashion",
      isFavorite: false,
      time: '6:00 PM',
    ),
  ];
}
